on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
    - name: Run linters  
      run: npm run lint
    - name: Run the test  
      run: npm test    
    - name: Sonar
      uses: SonarSource/sonarcloud-github-action@master
      env:        
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
    - name: Run the test  
      run: npm test    
    - name: Build
      run: npm run build    
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'OscarGelvez'
        user_email: 'oscargelvez23@gmail.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_FIND_HOTEL }}
        repository: ${{ github.repository }}  
        
